# IPL 2023 Data Cleaning and Preprocessing

This notebook focuses on cleaning and preparing IPL 2023 ball-by-ball data for analysis. We will handle missing values, check for inconsistencies, and ensure the dataset is in optimal shape for further exploration.

## 1. Importing Required Libraries

Importing essential Python libraries for data manipulation (`pandas`) and numerical computations (`numpy`), which will be used for cleaning, exploring, and analyzing the IPL dataset efficiently.

In [1]:
import pandas as pd
import numpy as np

## 2. Loading the Dataset

Loading the IPL dataset into a Pandas DataFrame to begin analysis. This step ensures the data is ready for exploration and cleaning.

In [2]:
df = pd.read_csv("ipl_2023_deliveries.csv")

## 3. Exploring the Dataset

Before diving into analysis, it's crucial to understand the dataset's structure, contents, and key statistics. This includes checking the number of rows and columns, previewing data, and summarizing numerical and categorical features to identify potential issues or patterns.

##### 3.1. Displays the number of rows and columns in the dataset.

In [3]:
df.shape

(17386, 20)

##### 3.2. Shows the first few rows to get an overview of the data.

In [4]:
df.head()

match_id  season  match_no          date                             venue  \
0    202301    2023         1  Mar 31, 2023  Narendra Modi Stadium, Ahmedabad   
1    202301    2023         1  Mar 31, 2023  Narendra Modi Stadium, Ahmedabad   
2    202301    2023         1  Mar 31, 2023  Narendra Modi Stadium, Ahmedabad   
3    202301    2023         1  Mar 31, 2023  Narendra Modi Stadium, Ahmedabad   
4    202301    2023         1  Mar 31, 2023  Narendra Modi Stadium, Ahmedabad   

  batting_team bowling_team  innings  over  striker bowler  runs_of_bat  \
0          CSK           GT        1   0.1   Conway  Shami            0   
1          CSK           GT        1   0.2   Conway  Shami            0   
2          CSK           GT        1   0.3  Gaikwad  Shami            0   
3          CSK           GT        1   0.4  Gaikwad  Shami            1   
4          CSK           GT        1   0.5   Conway  Shami            0   

   extras  wide  legbyes  byes  noballs wicket_type player_dismissed fielder  
0       0     0        0     0        0         NaN              NaN     NaN  
1       1     0        1     0        0         NaN              NaN     NaN  
2       0     0        0     0        0         NaN              NaN     NaN  
3       0     0        0     0        0         NaN              NaN     NaN  
4       0     0        0     0        0         NaN              NaN     NaN

##### 3.3. Provides data types and missing value details for each column.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17386 entries, 0 to 17385
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   match_id          17386 non-null  int64  
 1   season            17386 non-null  int64  
 2   match_no          17386 non-null  int64  
 3   date              17386 non-null  object 
 4   venue             17386 non-null  object 
 5   batting_team      17386 non-null  object 
 6   bowling_team      17386 non-null  object 
 7   innings           17386 non-null  int64  
 8   over              17386 non-null  float64
 9   striker           17386 non-null  object 
 10  bowler            17386 non-null  object 
 11  runs_of_bat       17386 non-null  int64  
 12  extras            17386 non-null  int64  
 13  wide              17386 non-null  int64  
 14  legbyes           17386 non-null  int64  
 15  byes              17386 non-null  int64  
 16  noballs           17386 non-null  int64 

##### 3.4. Gives statistical summaries like mean, min, and max for numerical columns.

In [6]:
df.describe()

match_id   season      match_no      innings          over  \
count   17386.000000  17386.0  17386.000000  17386.00000  17386.000000   
mean   202336.503278   2023.0     36.503278      1.48286      9.670355   
std        21.041748      0.0     21.041748      0.49972      5.713577   
min    202301.000000   2023.0      1.000000      1.00000      0.100000   
25%    202318.000000   2023.0     18.000000      1.00000      4.600000   
50%    202336.000000   2023.0     36.000000      1.00000      9.500000   
75%    202354.000000   2023.0     54.000000      2.00000     14.500000   
max    202374.000000   2023.0     74.000000      2.00000     19.600000   

        runs_of_bat        extras          wide       legbyes          byes  \
count  17386.000000  17386.000000  17386.000000  17386.000000  17386.000000   
mean       1.367480      0.070114      0.035086      0.013229      0.002243   
std        1.725766      0.347018      0.184002      0.114258      0.047310   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        1.000000      0.000000      0.000000      0.000000      0.000000   
75%        1.000000      0.000000      0.000000      0.000000      0.000000   
max        6.000000      5.000000      1.000000      1.000000      1.000000   

            noballs  
count  17386.000000  
mean       0.005637  
std        0.074868  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000

## 4. Handling Missing Values

Handling missing values is a crucial step in data cleaning to ensure the dataset is complete and reliable for analysis. This involves identifying missing values, understanding their impact, and applying appropriate techniques like filling, replacing, or dropping them based on the context of the data.

The `df.isnull().sum()` function counts the number of missing values in each column, helping us identify incomplete data.

In [7]:
df.isnull().sum()

match_id                0
season                  0
match_no                0
date                    0
venue                   0
batting_team            0
bowling_team            0
innings                 0
over                    0
striker                 0
bowler                  0
runs_of_bat             0
extras                  0
wide                    0
legbyes                 0
byes                    0
noballs                 0
wicket_type         16501
player_dismissed    16503
fielder             16708
dtype: int64

The missing values summary reveals that most columns are complete, but `wicket_type`, `player_dismissed`, and `fielder` have a significant number of missing values. These columns are related to dismissals, meaning missing values likely indicate deliveries where no wicket was taken.

 Additionally, there is a slight inconsistency, as `player_dismissed` has two more missing values than `wicket_type`, which suggests possible data redundancy or errors. It is addressed by the following code.
 

In [8]:
df[df['wicket_type'].notna() & df['player_dismissed'].isna()]

match_id  season  match_no          date  \
8925     202337    2023        37  Apr 27, 2023   
10555    202344    2023        44  May 02, 2023   

                                  venue batting_team bowling_team  innings  \
8925     Sawai Mansingh Stadium, Jaipur           RR          CSK        1   
10555  Narendra Modi Stadium, Ahmedabad           DC           GT        1   

       over      striker         bowler  runs_of_bat  extras  wide  legbyes  \
8925   19.4     Padikkal      Pathirana            0       1     1        0   
10555   1.2  Priyam Garg  Hardik Pandya            0       1     0        0   

       byes  noballs wicket_type player_dismissed      fielder  
8925      0        0      runout              NaN        Dhoni  
10555     0        1      runout              NaN  Rashid Khan

We identified two instances where a runout occurred but the `player_dismissed` column was missing values. After inspecting nearby rows, we determined whether the dismissed player was the striker or non-striker. We manually filled in these missing values to ensure consistency and accuracy in the dataset, preserving the integrity of the dismissal records.

In [9]:
# Manually update the two missing player_dismissed values
# Replacing with actual names found from the previous cels of the dataset
df.loc[df["player_dismissed"].isna() & df["wicket_type"].notna(), "player_dismissed"] = ["Dhruv Jurel", "Warner"]  

In [10]:
df.loc[[8925, 10555]]

match_id  season  match_no          date  \
8925     202337    2023        37  Apr 27, 2023   
10555    202344    2023        44  May 02, 2023   

                                  venue batting_team bowling_team  innings  \
8925     Sawai Mansingh Stadium, Jaipur           RR          CSK        1   
10555  Narendra Modi Stadium, Ahmedabad           DC           GT        1   

       over      striker         bowler  runs_of_bat  extras  wide  legbyes  \
8925   19.4     Padikkal      Pathirana            0       1     1        0   
10555   1.2  Priyam Garg  Hardik Pandya            0       1     0        0   

       byes  noballs wicket_type player_dismissed      fielder  
8925      0        0      runout      Dhruv Jurel        Dhoni  
10555     0        1      runout           Warner  Rashid Khan

Now we have resolved the redundancy issue in the dismissal records but there are still missing values in the dataset that need to be addressed. We will now focus on handling these null values appropriately to ensure data completeness and reliability.

In [11]:
df.isnull().sum()

match_id                0
season                  0
match_no                0
date                    0
venue                   0
batting_team            0
bowling_team            0
innings                 0
over                    0
striker                 0
bowler                  0
runs_of_bat             0
extras                  0
wide                    0
legbyes                 0
byes                    0
noballs                 0
wicket_type         16501
player_dismissed    16501
fielder             16708
dtype: int64

The below command fills the missing values in the dataset by assigning 'Not Out' to `wicket_type`, 'No One' to `player_dismissed`, and 'No One' to `fielder`. This ensures that all missing values in these columns are handled appropriately, maintaining consistency in the data.

In [12]:
df.fillna({"wicket_type": "Not Out", "player_dismissed": "No One",  "fielder": "No One"}, inplace=True)

In [13]:
df.isnull().sum()

match_id            0
season              0
match_no            0
date                0
venue               0
batting_team        0
bowling_team        0
innings             0
over                0
striker             0
bowler              0
runs_of_bat         0
extras              0
wide                0
legbyes             0
byes                0
noballs             0
wicket_type         0
player_dismissed    0
fielder             0
dtype: int64

Now that we have filled all missing values, our dataset is complete. The next step is to validate the logical consistency of the data, ensuring that all values align with real-world scenarios and there are no discrepancies in the dataset.

Pandas interprets "None" as NaN if the column’s data type is numerical or mixed-type. Therefore forcing it to string datatype.

In [14]:
df["wicket_type"] = df["wicket_type"].astype(str)
df["player_dismissed"] = df["player_dismissed"].astype(str)
df["fielder"] = df["fielder"].astype(str)

This will force pandas to recognize them as proper string values and not NaN

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17386 entries, 0 to 17385
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   match_id          17386 non-null  int64  
 1   season            17386 non-null  int64  
 2   match_no          17386 non-null  int64  
 3   date              17386 non-null  object 
 4   venue             17386 non-null  object 
 5   batting_team      17386 non-null  object 
 6   bowling_team      17386 non-null  object 
 7   innings           17386 non-null  int64  
 8   over              17386 non-null  float64
 9   striker           17386 non-null  object 
 10  bowler            17386 non-null  object 
 11  runs_of_bat       17386 non-null  int64  
 12  extras            17386 non-null  int64  
 13  wide              17386 non-null  int64  
 14  legbyes           17386 non-null  int64  
 15  byes              17386 non-null  int64  
 16  noballs           17386 non-null  int64 

## 5. Data Validation and Manipulation

In this section, we will verify the correctness of each column's data by checking for inconsistencies, logical errors, and unexpected values. Any necessary transformations or corrections will also be applied to ensure data integrity

##### 5.1. match_id :

In [16]:
df["match_id"].unique()

array([202301, 202302, 202303, 202304, 202305, 202306, 202307, 202308,
       202309, 202310, 202311, 202312, 202313, 202314, 202315, 202316,
       202317, 202318, 202319, 202320, 202321, 202322, 202323, 202324,
       202325, 202326, 202327, 202328, 202329, 202330, 202331, 202332,
       202333, 202334, 202335, 202336, 202337, 202338, 202339, 202340,
       202341, 202342, 202343, 202344, 202345, 202346, 202347, 202348,
       202349, 202350, 202351, 202352, 202353, 202354, 202355, 202356,
       202357, 202358, 202359, 202360, 202361, 202362, 202363, 202365,
       202366, 202367, 202368, 202369, 202370, 202371, 202373, 202374])

This command returns an array of unique match IDs present in the dataset. The output helps in verifying the total number of matches recorded and checking for any duplicate or missing match IDs. We found 2 matches missing out of total 74 matches happened.( We are not going to fix it since whole match is missing which can't be populated with the available data)

##### 5.2. season :

In [17]:
df["season"].unique()

array([2023])

One unique season - 2023

##### 5.3. match_no :

In [18]:
df["match_no"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 65, 66, 67, 68, 69,
       70, 71, 73, 74])

As explained earlier, we observed that two matches are missing from the dataset. This means our analysis will be based on the available matches, which are slightly fewer than the expected total.

##### 5.4. date :

As noted from the `info()` command, our `date` column is currently stored as an `object` (string) data type. To perform date-based operations efficiently, we need to convert it into the `datetime64` format. This will allow us to handle time-based analysis, sorting, and filtering more effectively.

In [19]:
df["date"] = pd.to_datetime(df["date"])

Now, we have changed it into `datetime64` format. We can verify it by the following commands.

In [20]:
df["date"].dtype

dtype('<M8[ns]')

In [21]:
df.head()

match_id  season  match_no       date                             venue  \
0    202301    2023         1 2023-03-31  Narendra Modi Stadium, Ahmedabad   
1    202301    2023         1 2023-03-31  Narendra Modi Stadium, Ahmedabad   
2    202301    2023         1 2023-03-31  Narendra Modi Stadium, Ahmedabad   
3    202301    2023         1 2023-03-31  Narendra Modi Stadium, Ahmedabad   
4    202301    2023         1 2023-03-31  Narendra Modi Stadium, Ahmedabad   

  batting_team bowling_team  innings  over  striker bowler  runs_of_bat  \
0          CSK           GT        1   0.1   Conway  Shami            0   
1          CSK           GT        1   0.2   Conway  Shami            0   
2          CSK           GT        1   0.3  Gaikwad  Shami            0   
3          CSK           GT        1   0.4  Gaikwad  Shami            1   
4          CSK           GT        1   0.5   Conway  Shami            0   

   extras  wide  legbyes  byes  noballs wicket_type player_dismissed fielder  
0       0     0        0     0        0     Not Out           No One  No One  
1       1     0        1     0        0     Not Out           No One  No One  
2       0     0        0     0        0     Not Out           No One  No One  
3       0     0        0     0        0     Not Out           No One  No One  
4       0     0        0     0        0     Not Out           No One  No One

##### 5.5. venue :

In [22]:
df["venue"].unique()

array(['Narendra Modi Stadium, Ahmedabad',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
       'Rajiv Gandhi International Stadium, Hyderabad',
       'M.Chinnaswamy Stadium, Bengaluru',
       'MA Chidambaram Stadium, Chennai', 'Arun Jaitley Stadium, Delhi',
       'Barsapara Cricket Stadium, Guwahati', 'Eden Gardens, Kolkata',
       'Wankhede Stadium, Mumbai', 'Sawai Mansingh Stadium, Jaipur',
       'Himachal Pradesh Cricket Association Stadium, Dharamsala'],
      dtype=object)

IPL 2023: In total 12 venues - Mohali, Lucknow, Hyderabad, Bengaluru, Chennai, Delhi, Kolkata, Jaipur, Mumbai, Guwahati (Royals' second home) and Dharamsala (Kings' second home) will host the IPL 2023 matches.

##### 5.6. batting_team and bowling_team :

In [23]:
df["batting_team"].unique()

array(['CSK', 'GT', 'PBKS', 'KKR', 'LSG', 'DC', 'RR', 'SRH', 'MI', 'RCB'],
      dtype=object)

In [24]:
df["bowling_team"].unique()

array(['GT', 'CSK', 'KKR', 'PBKS', 'DC', 'LSG', 'SRH', 'RR', 'RCB', 'MI'],
      dtype=object)

We have 10 unique teams participating in the IPL 2023 season. Additionally, we are verifying that no team is playing against itself in any match, ensuring that the dataset correctly represents valid matchups between different teams.

In [25]:
len(df[df['batting_team'] == df['bowling_team']])

0

##### 5.6. innings :

In [26]:
df["innings"].unique()

array([1, 2])

##### 5.7. over :

In [27]:
df["over"].unique()

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  1.1,  1.2,  1.3,  1.4,  1.5,
        1.6,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  3.1,  3.2,  3.3,  3.4,
        3.5,  3.6,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  5.1,  5.2,  5.3,
        5.4,  5.5,  5.6,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  7.1,  7.2,
        7.3,  7.4,  7.5,  7.6,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  9.1,
        9.2,  9.3,  9.4,  9.5,  9.6, 10.1, 10.2, 10.3, 10.4, 10.5, 10.6,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 12.1, 12.2, 12.3, 12.4, 12.5,
       12.6, 13.1, 13.2, 13.3, 13.4, 13.5, 13.6, 14.1, 14.2, 14.3, 14.4,
       14.5, 14.6, 15.1, 15.2, 15.3, 15.4, 15.5, 15.6, 16.1, 16.2, 16.3,
       16.4, 16.5, 16.6, 17.1, 17.2, 17.3, 17.4, 17.5, 17.6, 18.1, 18.2,
       18.3, 18.4, 18.5, 18.6, 19.1, 19.2, 19.3, 19.4, 19.5, 19.6])

No. of Balls per innings

In [28]:
df["over"].nunique()

120

##### 5.8. striker and bowler :

We are verifying that the striker and bowler are never the same player in any given delivery. This ensures the dataset correctly represents a valid game scenario where a batsman faces a bowler, and self-bowling does not occur.

In [29]:
len(df[df['striker'] == df['bowler']])

0

##### 5.9. runs_of_bat, extras and others:

This command retrieves all unique values in the `runs_of_bat` column, showing the different possible runs scored on a legal delivery. The expected values are 0, 1, 2, 3, 4, and 6, but we need to check if any unexpected values (like 5) appear.

In [30]:
df["runs_of_bat"].unique()

array([0, 1, 4, 6, 2, 3, 5])

In [31]:
len(df[df["runs_of_bat"] == 5])

1

The presence of **5 runs** in the `runs_of_bat` column indicates a rare event that occurred once in IPL 2023. This could have been due to an overthrow or an unusual fielding error. While uncommon, it is a valid outcome and does not require data correction.

In [32]:
df["extras"].unique()

array([0, 1, 4, 5, 2, 3])

In [33]:
df["wide"].unique()

array([0, 1])

In [34]:
df["legbyes"].unique()

array([0, 1])

In [35]:
df["byes"].unique()

array([0, 1])

In [36]:
df["noballs"].unique()

array([0, 1])

This query checks for instances where runs have been scored off the bat (`runs_of_bat` > 0) while also having extras like wide, leg byes, or byes in the same delivery.

In [37]:
df[((df["wide"] > 0) | (df["legbyes"] > 0) | (df["byes"] > 0)) & (df["runs_of_bat"] > 0) ]

Empty DataFrame
Columns: [match_id, season, match_no, date, venue, batting_team, bowling_team, innings, over, striker, bowler, runs_of_bat, extras, wide, legbyes, byes, noballs, wicket_type, player_dismissed, fielder]
Index: []

In cricket rules, if a ball is declared wide, leg bye, or bye, the batsman does not get runs from the bat (`runs_of_bat`). So ideally, there shouldn't be any rows that satisfy both conditions

##### 5.10. wicket_type, player_dismissed and fielder :

In [38]:
df["wicket_type"].unique()

array(['Not Out', 'bowled', 'caught', 'lbw', 'stumped', 'runout',
       'hit wicket'], dtype=object)

This query filters out cases where a wicket was taken but no fielder is recorded, even though the dismissal type requires one.
For bowled, lbw, and hit wicket, a fielder is not needed, so they are excluded in the condition.

In [39]:
df[(df["fielder"] == "No One") & ~df["wicket_type"].isin(["bowled", "lbw", "hit wicket", "Not Out"])]

Empty DataFrame
Columns: [match_id, season, match_no, date, venue, batting_team, bowling_team, innings, over, striker, bowler, runs_of_bat, extras, wide, legbyes, byes, noballs, wicket_type, player_dismissed, fielder]
Index: []

Since no rows appeared, it confirms that every dismissal requiring a fielder has one recorded properly. This indicates that our data is logically consistent in this aspect

## 6. Saving the Cleaned Dataset

Now that we have cleaned and validated our IPL 2023 dataset, we save it as a CSV file. This ensures that our refined data is readily available for further analysis and visualization without needing to repeat the preprocessing steps.

In [40]:
df.to_csv("cleansed_ipl_2023_deliveries.csv", index = False )

## 7. Conclusion

In this analysis, we systematically cleaned and validated the IPL 2023 dataset by handling missing values, fixing redundancies, and verifying logical consistency. We ensured that each column's data adhered to expected patterns, correcting any inconsistencies where necessary. While two matches were missing from the dataset, we proceeded with the best available data to maintain accuracy. Now, we save the cleaned dataset as a CSV file, making it ready for further analysis, including team performance evaluation, player statistics, and match trend insights.